//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUS
    {
        public int Bus_id { get; set; }
        public string Bus_CompanyName { get; set; }
        public string Bus_number { get; set; }
        public string Password { get; set; }
        public int CaseId { get; set; }
    }
}
