//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int Case_id { get; set; }
        public int P_id { get; set; }
        public string P_rank { get; set; }
        public string Area { get; set; }
        public string Case_type { get; set; }
        public System.TimeSpan Case_time { get; set; }
    
        public virtual Police Police { get; set; }
    }
}
